# Pytorch Practice Notebook

1. https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [ ]:
# !pip install torch
# !pip install torchvision 

In [108]:
import torch
import numpy as np

## Creating Tensors

In [7]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(type(data), type(x_data))

<class 'list'> <class 'torch.Tensor'>


In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(type(np_array), type(x_np))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [10]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(x_ones, x_rand)

tensor([[1, 1],
        [1, 1]]) tensor([[0.9289, 0.8217],
        [0.0112, 0.8856]])


In [19]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)
# rand_tensor
# ones_tensor
# zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
tensor = torch.rand((3,4))

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [23]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

cpu


In [27]:
tensor[:,1]=0
tensor

tensor([[0.7004, 0.0000, 0.1404, 0.7058],
        [0.0048, 0.0000, 0.6230, 0.5981],
        [0.0205, 0.0000, 0.7260, 0.4469]])

In [26]:
tensor[:2]

tensor([[0.7004, 0.1042, 0.1404, 0.7058],
        [0.0048, 0.4376, 0.6230, 0.5981]])

In [34]:
torch.cat([tensor,tensor,tensor], dim=1)

tensor([[0.7004, 0.0000, 0.1404, 0.7058, 0.7004, 0.0000, 0.1404, 0.7058, 0.7004,
         0.0000, 0.1404, 0.7058],
        [0.0048, 0.0000, 0.6230, 0.5981, 0.0048, 0.0000, 0.6230, 0.5981, 0.0048,
         0.0000, 0.6230, 0.5981],
        [0.0205, 0.0000, 0.7260, 0.4469, 0.0205, 0.0000, 0.7260, 0.4469, 0.0205,
         0.0000, 0.7260, 0.4469]])

In [35]:
tensor.mul(tensor)

tensor([[4.9059e-01, 0.0000e+00, 1.9714e-02, 4.9814e-01],
        [2.3022e-05, 0.0000e+00, 3.8811e-01, 3.5776e-01],
        [4.1988e-04, 0.0000e+00, 5.2705e-01, 1.9969e-01]])

In [36]:
tensor*tensor

tensor([[4.9059e-01, 0.0000e+00, 1.9714e-02, 4.9814e-01],
        [2.3022e-05, 0.0000e+00, 3.8811e-01, 3.5776e-01],
        [4.1988e-04, 0.0000e+00, 5.2705e-01, 1.9969e-01]])

In [37]:
tensor.matmul(tensor.T)

tensor([[1.0084, 0.5130, 0.4317],
        [0.5130, 0.7459, 0.7197],
        [0.4317, 0.7197, 0.7272]])

In [39]:
tensor@tensor.T

tensor([[1.0084, 0.5130, 0.4317],
        [0.5130, 0.7459, 0.7197],
        [0.4317, 0.7197, 0.7272]])

In [41]:
tensor.add_(5)

tensor([[5.7004, 5.0000, 5.1404, 5.7058],
        [5.0048, 5.0000, 5.6230, 5.5981],
        [5.0205, 5.0000, 5.7260, 5.4469]])

In [42]:
t = torch.ones(3)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1.])
[1. 1. 1.]


In [43]:
t.add_(1)

tensor([2., 2., 2.])

In [44]:
n

array([2., 2., 2.], dtype=float32)

In [46]:
n = np.ones(5)
t = torch.from_numpy(n)

print(n,t)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [49]:
np.add(n,1, out=n)

array([2., 2., 2., 2., 2.])

In [50]:
t

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [53]:
from torchvision.models import resnet18, ResNet18_Weights

In [55]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /home/dranzer/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 44.7M/44.7M [00:01<00:00, 26.9MB/s]


In [58]:
prediction = model(data)

In [64]:
loss = (prediction - labels).sum()

In [65]:
loss.backward()

In [67]:
optim = torch.optim.SGD(model.parameters(), lr = 1e-2, momentum=0.9)

In [69]:
optim.step()

In [84]:
a = torch.tensor([2.,3.], requires_grad=True)
b = torch.tensor([6.,4.], requires_grad=True)

In [85]:
Q = 3*a**3 - b**2

In [86]:
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [93]:
external_grad = torch.tensor([1.,1.])

In [94]:
Q.backward(gradient=external_grad)

In [97]:
9*a**2==a.grad

tensor([True, True])

In [98]:
-2*b==b.grad

tensor([True, True])

In [102]:
from torch import nn, optim

model = resnet18(weights=ResNet18_Weights.DEFAULT)
for param in model.parameters():
    param.requires_grad = False

In [103]:
model.fc = nn.Linear(512,10)

In [104]:
optimizer = optim.SGD(model.parameters(), lr = 1e-2, momentum=0.9)

In [107]:
model.parameters

<bound method Module.parameters of ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)


## Training a Neural Net

In [148]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [149]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        ## 1 input channel, 6 output channels, 5x5 square convolution kernel
        self.conv1 = nn.Conv2d(1,6,5)
        ## 6 input channels, 16 output channels, 5x5 convolution kernel
        self.conv2 = nn.Conv2d(6,16,5)
        ## y = Wx + b
        self.fc1 = nn.Linear(16*5*5,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, input):
        ## convolution layer c1
        ## output tensor size: (N, 6, 28, 28) where N is the batch size
        c1 = F.relu(self.conv1(input))
#         print(c1.shape)
        ## Subsampling Layer s2 with 2x2 grid
        ## output tensor: (N, 16, 14, 14)
        s2 = F.max_pool2d(c1, (2,2))
        ## Convolutional Layer c3: N,16,10,10
        c3 = F.relu(self.conv2(s2))
        ## Subsampling layer s4: N, 16, 5, 5
        s4 = F.max_pool2d(c3, 2)
        ## flatten s4: N, 16*5*5
        s4 = torch.flatten(s4, 1)
        ## Fully connected layer: N, 120
        f5 = F.relu(self.fc1(s4))
        ## Fully connected layer: N,84
        f6 = F.relu(self.fc2(f5))
        ## fully connected layer: N, 10
        output = F.relu(self.fc3(f6))
        return output

net = Net()
print(net)
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [150]:
params = list(net.parameters())
print(len(params))
print(params[2].shape)

10
torch.Size([16, 6, 5, 5])


In [151]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

torch.Size([1, 6, 28, 28])
tensor([[0.0000e+00, 0.0000e+00, 7.0180e-02, 1.1379e-04, 0.0000e+00, 1.5516e-01,
         0.0000e+00, 0.0000e+00, 7.5758e-02, 7.2605e-02]],
       grad_fn=<ReluBackward0>)


In [152]:
# net.zero_grad()

In [153]:
# out.backward(torch.randn(1,10))

In [154]:
# out.shape

In [155]:
target = torch.randn(10)
target = target.view(1,-1)
criterion = nn.MSELoss()

In [156]:
loss = criterion(out,target)
print(loss)

tensor(1.5457, grad_fn=<MseLossBackward0>)


In [157]:
loss.grad_fn

In [158]:
from torch.autograd.grad_mode import get_printable_graph
print(get_printable_graph(loss.grad_fn))

ImportError: cannot import name 'get_printable_graph' from 'torch.autograd.grad_mode' (/home/dranzer/py3/lib/python3.8/site-packages/torch/autograd/grad_mode.py)

In [159]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [160]:
net.zero_grad()
print(f"conv1.bias.grad before backward: {net.conv1.bias.grad}")
loss.backward()
print(f"conv1.bias.grad after backward: {net.conv1.bias.grad}")

conv1.bias.grad before backward: None
conv1.bias.grad after backward: tensor([ 0.0147, -0.0076,  0.0131, -0.0185, -0.0190,  0.0050])


In [162]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.01)
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()

torch.Size([1, 6, 28, 28])


## Training a Classifier

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms

In [2]:
%%time
transform = transforms.Compose(
    [transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))]
)
batch_size = 4
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainLoader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testLodaer = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=True, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

URLError: <urlopen error [Errno 110] Connection timed out>

In [3]:
import matplotlib.pyplot as plt
import numpy as np

def imshow(img):
    img = img/2+0.5
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1,2,0)))
    plt.show()
dataiter = iter(trainLoader)
images, labels = next(dataiter)

imshow(torchvision.utils.make_grid(images))
print(' '.join(f'{classes[labels[j]]:5s}' for j in range(batch_size)))

NameError: name 'trainLoader' is not defined

In [5]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3,6,5)
        self.pool = nn.MaxPool2d(2,1)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84,10)
        
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x,1)
        x - F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
net = Net()
        

In [9]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr= 0.01, momentum=0.9)

In [10]:
for epoch in range(2):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(ouput, labels)
        loss.backward()
        optimzer.step()
        
        running_loss = loss.item()
        if i%2000 == 1999:
            print(f"[{epoch+1}, {i+1:5d}] loss: {running_loss/2000:.3f}")
            runnning_loss = 0.0
    print('FInished Training')

NameError: name 'trainloader' is not defined